account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from account.views import *

app_name = 'account'

urlpatterns = [
    path('create/', AccountCreate.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetail.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdate.as_view(), name='update'),
    path('delete/<int:pk>', AccountDelete.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import *

app_name = 'articleApp'

urlpatterns = [
    # path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('list/', ArticleListView.as_view(), name='list'),
]

gis_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('profile/', include('profileApp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentApp.urls')),
    path('projects/', include('projectApp.urls')),
    path('subscribe/', include('subscribeApp.urls')),
    path('likes/', include('likeApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectApp/urls.py
from django.urls import path

from projectApp.views import *

app_name = 'projectApp'

urlpatterns = [
    path('create/', ProjectCreationView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeApp/urls.py
from django.urls import path

from subscribeApp.views import *

app_name = 'subscribeApp'

urlpatterns = [
    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),
    path('list', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body style="font-family: NanumSquareR">
{% include 'header.html' %}

<hr>
{% for message in messages %}
    <div>
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        </div>
    </div>
{% endfor %}
{% block content %}

{% endblock %}
<hr>
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="pragmatic_footer_button">
    <div>
        <span>공지사항</span>
        <span>제품 문의</span>
        <span>고객 서비스</span>
        <span></span>
    </div >
    <div class="pragmatic_footer_logo">
        <h5>Pragmatic</h5>
    </div>
</div>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    <style>
        body div{
            text-align: center;
        }
    </style>
</head>
<style>
    @font-face {
        font-family: 'NanumSquareR';
        src: local('NanumSquareR'),
        url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'NanumSquareEB';
        src: local('NanumSquareEB'),
        url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'NanumSquareB';
        src: local('NanumSquareB'),
        url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'NanumSquareL';
        src: local('NanumSquareL'),
        url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
    }
</style>

templates/header.html
<div>
    <div class="pragmatic_header_logo">
        <h1>
            <a href="{% url 'home' %}">
                제에에에에목
            </a>
        </h1>
    </div>
    <div class="pragmatic_header_button">
        <span class='mx-2'>
            <a href="{% url 'articleApp:list' %}">
                그으으으으으을
            </a>
        </span>
        <span class='mx-2'>
            <a href="{% url 'projectApp:list' %}">
                게시판
            </a>
        </span>
        {% if not user.is_authenticated %}
        <span class='mx-2'>
            <a href="{% url 'account:login' %}">로그인</a>
        </span>
        <span class='mx-2'>
            <a href="{% url 'account:create' %}">회원가입</a>
        </span>
        {% else %}
        <span class='mx-2'>
            <a href="{% url 'subscribeApp:list' %}">구독</a>
        </span>
        <span class='mx-2'>
            <a href="{% url 'account:detail' pk=user.pk %}">내정보</a>
        </span>
        <span class='mx-2'>
            <a href="{% url 'account:logout' %}">로그아웃</a>
        </span>
        {% endif %}
    </div>
</div>

templates/hello_world.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body>
{% include 'header.html' %}


{% block content %}

{% endblock %}

{% include 'footer.html' %}
</body>
</html>